### PR TITLE
Handle PropertyConverter if DisableFetchingTableMetadata is used

### LINKED ISSUE #3303: DisableFetchingTableMetadata leads to key exception if PropertyConverter is used
### Describe the bug

DisableFetchingTableMetadata does not account for PropertyConverters. See repro.

### Expected Behavior

It shouldn't fail trying to save item with a strange message.

### Current Behavior

System.InvalidOperationException: 'Key attribute Type must be of type Numeric'

### Reproduction Steps

<details>
  <summary>Repro</summary>

```csharp
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;
using Amazon.Runtime;

var config = new AmazonDynamoDBConfig { ServiceURL = $"http://localhost:8000" };
var credentials = new BasicAWSCredentials("access", "secret");
var dynamoDbClient = new AmazonDynamoDBClient(credentials, config);
var context = new DynamoDBContext(dynamoDbClient, new DynamoDBContextConfig
{
    DisableFetchingTableMetadata = true
});

var tables = await dynamoDbClient.ListTablesAsync();
if (!tables.TableNames.Contains("TestTable"))
{
    await dynamoDbClient.CreateTableAsync(new CreateTableRequest
    {
        TableName = "TestTable",
        AttributeDefinitions =
        [
            new AttributeDefinition
            {
                AttributeName = "Type",
                AttributeType = ScalarAttributeType.S
            },
            new AttributeDefinition
            {
                AttributeName = "Id",
                AttributeType = ScalarAttributeType.S
            }
        ],
        KeySchema =
        [
            new KeySchemaElement
            {
                AttributeName = "Type",
                KeyType = KeyType.HASH
            },
            new KeySchemaElement
            {
                AttributeName = "Id",
                KeyType = KeyType.RANGE
            }
        ],
        ProvisionedThroughput = new ProvisionedThroughput
        {
            ReadCapacityUnits = 1,
            WriteCapacityUnits = 1
        }
    });

    Console.WriteLine("Table created");
}

await context.SaveAsync(new TestType
{
    Id = "1",
    Type = TypeEnum.Value2,
    Name = "Test",
});
Console.WriteLine("Item saved.");

var item = await context.LoadAsync<TestType>(TypeEnum.Value2, "1");
Console.WriteLine($"Item loaded: {item}");

[DynamoDBTable("TestTable")]
record class TestType
{
    [DynamoDBHashKey]
    [DynamoDBProperty(Converter = typeof(EnumAsStringConverter<TypeEnum>))]
    public TypeEnum Type { get; set; }

    [DynamoDBRangeKey]
    public string Id { get; set; }

    public string Name { get; set; }
}

enum TypeEnum
{
    Value1,
    Value2
}

public class EnumAsStringConverter<T> : IPropertyConverter where T : struct
{
    public object FromEntry(DynamoDBEntry entry) => Enum.Parse<T>(entry.AsString());
    public DynamoDBEntry ToEntry(object value) => new Primitive(value.ToString());
}
```

</details>

The code abode fails with an exception:
System.InvalidOperationException: 'Key attribute Type must be of type Numeric'

It works fine if I set DisableFetchingTableMetadata to false.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS .NET SDK and/or Package version used

Amazon.Lambda.DynamoDBEvents 3.7.302.19

### Targeted .NET Platform

.NET 8

### Operating System and version

AmazonLinuix

### PR DESCRIPTION
**Pull request by Dreamescaper**
## Description
Fixes #3303 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by dscpinheiro** [comment]
Yes, you can run them locally by opening the service specific solution (`sdk\src\Services\DynamoDBv2\DynamoDBv2.sln`), but the SDK integration tests always run targeting actual AWS services.

The existing tests for `DisableFetchingTableMetadata` are in this file: https://github.com/aws/aws-sdk-net/blob/b5b386ac678bd3aeacaf7a11681bf246565dc592/sdk/test/Services/DynamoDBv2/IntegrationTests/DataModelTests.cs

**Comment by Dreamescaper** [comment]
@dscpinheiro 
Don't I need some AWS credentials to run them?

**Comment by dscpinheiro** [comment]
Yes, it's called out in the `README` (although I see it's not exactly easy to find...): https://github.com/aws/aws-sdk-net?tab=readme-ov-file#tests
> Integration tests can be found in the AWSSDK.IntegrationTests project. These test assume that a default profile has been configured for credentials. For information about setting up a default profile read the [Developer Guide](http://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-config-creds.html).

File: sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs [hunk 1]
```diff
@@ -532,7 +545,7 @@ internal static Table CreateTableFromItemStorageConfig(IAmazonDynamoDB client, T
 
                 table.Attributes.Add(new AttributeDefinition { AttributeName = property.AttributeName, AttributeType = PrimitiveToScalar(primitiveType) });
             }
-
```
Comment (danielmarbach) [inline sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs:535]: It would be great if the SDK had editor config support to highlight these // @normj

File: sdk/test/Services/DynamoDBv2/IntegrationTests/DataModelTests.cs [hunk 2]
```diff
@@ -158,6 +157,32 @@ public void TestContext_DisableFetchingTableMetadata_DateTimeAsHashKey()
...
+            CreateContext(DynamoDBEntryConversion.V2, true, true);
+
+            var employee = new PropertyConverterEmployee
+            {
+                Name = Status.Active,
+                CreationTime = EpochDate,
+            };
+
+            await Context.SaveAsync(employee);
+            var storedEmployee = await Context.LoadAsync<PropertyConverterEmployee>(employee.CreationTime, employee.Name);
```
Comment (ashovlin) [inline sdk/test/Services/DynamoDBv2/IntegrationTests/DataModelTests.cs:180]: These tests are still included in `AWSSDK.IntegrationTests.DynamoDBv2.Net35`, which doesn't have `Task` or the async methods on `Context`.

Can you adjust to `public void` and use the sync `Save` and `Load` methods instead?

**Review by ashovlin — CHANGES_REQUESTED** [review]
Looks good functionally, but one comment on the new test

File: sdk/test/Services/DynamoDBv2/IntegrationTests/DataModelTests.cs (hunk 2 above)
Comment (Dreamescaper) [reply sdk/test/Services/DynamoDBv2/IntegrationTests/DataModelTests.cs]: done

**Comment by ashovlin** [comment]
This looks good, and passed on our internal build system. I've prepared in the versioning metadata in #3310 , and will line up a second reviewer from the team.

**Review by ashovlin — APPROVED** [review]

**Review by dscpinheiro — APPROVED** [review]

**Comment by ashovlin** [comment]
Merged to our staging branch. This should go out in today's release, will reply again with the version number once it's finished.

**Comment by ashovlin** [comment]
This shipped yesterday in AWSSDK.DynamoDBv2 version 3.7.302.26. Thanks again for your contribution!
